const KEY='hukuk50k-os-v3';
const START='2026-09-07';
const LAW_STRETCH_RANK=30000;
const LAW_MIN_RANK=50000;
const BASE_SALARY=15000;
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clone=o=>JSON.parse(JSON.stringify(o));
const pad=n=>String(n).padStart(2,'0');
const dateKey=d=>{const x=d instanceof Date?d:new Date(d);return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`};
const today=()=>dateKey(new Date());
const addDays=(k,n)=>{const d=new Date(k+'T12:00:00');d.setDate(d.getDate()+n);return dateKey(d)};
const fmtDate=k=>new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'short'}).format(new Date(k+'T12:00:00'));
const longDate=k=>new Intl.DateTimeFormat('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(k+'T12:00:00'));
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,6)}`;
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const curriculum={
  'TYT Türkçe':['Sözcükte Anlam','Cümlede Anlam','Paragraf','Ses Bilgisi','Yazım Kuralları','Noktalama İşaretleri','Sözcük Türleri','Fiiller','Cümlenin Ögeleri','Cümle Türleri','Anlatım Bozukluğu'],
  'TYT Matematik':['Temel Kavramlar','Sayı Basamakları','Bölme-Bölünebilme','EBOB-EKOK','Rasyonel Sayılar','Üslü Sayılar','Köklü Sayılar','Mutlak Değer','Basit Eşitsizlikler','Oran-Orantı','Denklem Çözme','Problemler','Kümeler','Fonksiyonlar','Permütasyon-Kombinasyon','Olasılık','Veri-İstatistik'],
  'TYT Geometri':['Doğruda Açılar','Üçgende Açılar','Üçgende Uzunluk','Üçgende Alan','Benzerlik','Çokgenler','Dörtgenler','Çember-Daire','Katı Cisimler','Analitik Geometri'],
  'TYT Sosyal':['Tarih Bilimine Giriş','İlk Türk Devletleri','İslam Tarihi','Osmanlı Siyasi Tarihi','Milli Mücadele','Atatürk İlkeleri','Coğrafyanın Temelleri','Türkiye Coğrafyası','Felsefeye Giriş','Din Kültürü Temelleri'],
  'TYT Fen':['Fizik Temelleri','Hareket-Kuvvet','İş-Güç-Enerji','Elektrik','Kimyanın Temelleri','Atom ve Periyodik Sistem','Kimyasal Türler','Maddenin Halleri','Biyoloji Bilimine Giriş','Hücre','Kalıtım'],
  'AYT Matematik':['Fonksiyonlar','Polinomlar','İkinci Dereceden Denklemler','Parabol','Eşitsizlikler','Trigonometri','Üstel ve Logaritmik Fonksiyonlar','Diziler','Permütasyon-Kombinasyon','Olasılık','Limit ve Süreklilik','Türev','İntegral','Analitik Geometri'],
  'AYT Edebiyat':['Edebiyat Bilgisi','Şiir Bilgisi','İslamiyet Öncesi Türk Edebiyatı','Geçiş Dönemi','Halk Edebiyatı','Divan Edebiyatı','Tanzimat','Servetifünun','Fecriati','Milli Edebiyat','Cumhuriyet Dönemi','Şiir Akımları','Roman-Hikâye','Tiyatro','Edebi Sanatlar'],
  'AYT Tarih-1':['Tarih ve Zaman','İlk ve Orta Çağlarda Türk Dünyası','Osmanlı Siyasi Tarihi','Osmanlı Kültür ve Medeniyeti','18-19. Yüzyıl Osmanlı','Milli Mücadele','Atatürk Dönemi İç ve Dış Politika'],
  'AYT Coğrafya-1':['Doğal Sistemler','Beşeri Sistemler','Ekonomik Faaliyetler','Türkiye Coğrafyası','Küresel Ortam','Çevre ve Toplum']
};
const areaOf=n=>n.startsWith('TYT')?'TYT':'AYT';
const habitDefs=[['sleep','7+ saat uyku','Temel enerji'],['study','Ders hedefi','Net çalışma'],['phone','Sosyal medya ≤45 dk','Odak'],['exercise','Antrenman / yürüyüş','Fizik'],['eb','EB Digital 60 dk','Ek gelir']];
const schedule=[['08:30','10:30','TYT / Matematik','120 dk • konu + soru','TYT'],['10:45','12:15','Türkçe / AYT Edebiyat','90 dk • aktif çalışma','EA'],['12:15','12:45','Paragraf + Problem','30 dk • günlük taban','Taban'],['13:30','14:30','EB Digital Studio','60 dk • para motoru','Para'],['15:00','15:30','Mini tekrar','30 dk • yanlışlar / kartlar','Tekrar']];
const baseTasks=()=>[
 {title:'TYT Matematik • 120 dk',category:'TYT',minutes:120,kind:'study'},
 {title:'Türkçe • 20 paragraf + yanlış analizi',category:'TYT',minutes:45,kind:'study'},
 {title:'AYT Edebiyat • 60 dk',category:'AYT',minutes:60,kind:'study'},
 {title:'Problem • 15 soru',category:'Tekrar',minutes:30,kind:'study'},
 {title:'EB Digital Studio • müşteri / portföy',category:'EB Digital',minutes:60,kind:'work'},
 {title:'Antrenman',category:'Spor',minutes:60,kind:'life'}
];
const defaultState={version:3,days:{},subjects:{},mocks:[],money:[],settings:{studyGoal:270,questionGoal:350,paragraphGoal:20,problemGoal:15},theme:'dark',focusSessions:0};
let state=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&x.version===3)return normalize(x)}catch{}return clone(defaultState)}
function normalize(x){x.days??={};x.subjects??={};x.mocks??=[];x.money??=[];x.settings={...defaultState.settings,...(x.settings||{})};x.focusSessions??=0;x.theme??='dark';return x}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function ensureDay(k=today()){if(!state.days[k])state.days[k]={tasks:baseTasks().map(t=>({...t,id:uid('task'),done:false})),habits:Object.fromEntries(habitDefs.map(x=>[x[0],false])),studyMinutes:0,questions:0,note:''};state.days[k].habits??=Object.fromEntries(habitDefs.map(x=>[x[0],false]));state.days[k].tasks??=[];return state.days[k]}
function taskPct(d){return d.tasks.length?Math.round(d.tasks.filter(t=>t.done).length/d.tasks.length*100):0}
function studyMinutes(d){return d.tasks.filter(t=>t.done&&['study','review'].includes(t.kind)).reduce((a,t)=>a+(Number(t.minutes)||0),0)+Number(d.studyMinutes||0)}
function questionCount(d){return Number(d.questions||0)}
function habitScore(d){return habitDefs.filter(([k])=>d.habits?.[k]).length}
function systemScore(d){return Math.round(taskPct(d)*.55+(habitScore(d)/habitDefs.length*100)*.30+(Math.min(100,studyMinutes(d)/state.settings.studyGoal*100)*.15))}
function streak(){let n=0;let k=today();for(let i=0;i<60;i++){const d=state.days[k];if(!d||systemScore(d)<70)break;n++;k=addDays(k,-1)}return n}
function allSubjects(){return Object.entries(curriculum)}
function topicStats(){let total=0,done=0,active=0;allSubjects().forEach(([name,topics])=>topics.forEach((_,i)=>{total++;const s=state.subjects[name]?.[i]?.status||state.subjects[name]?.[i]||'not_started';if(s==='done')done++;if(['learning','practice','review'].includes(s))active++}));return {total,done,active,pct:total?Math.round(done/total*100):0}}
function stateTopic(name,i){const raw=state.subjects[name]?.[i];if(typeof raw==='string')return {status:raw,confidence:0,last:'',next:''};return raw||{status:'not_started',confidence:0,last:'',next:''}}
function todayTasks(){return ensureDay().tasks}
function latestMocks(type){return state.mocks.filter(m=>!type||m.type===type).slice().sort((a,b)=>a.date.localeCompare(b.date))}
function lastStudyDays(n){const out=[];for(let i=n-1;i>=0;i--){const k=addDays(today(),-i),d=state.days[k];out.push({k,d,mins:d?studyMinutes(d):0,score:d?systemScore(d):0})}return out}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function applyTheme(){document.documentElement.dataset.theme=state.theme;$('#themeBtn').textContent=state.theme==='dark'?'☼':'☾'}
function navigate(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));const titles={dashboard:'Kontrol Merkezi',today:'Bugünün Sistemi',focus:'Focus Room',roadmap:'Konu Motoru',mock:'Deneme Merkezi',analytics:'Performans',discipline:'Disiplin Merkezi',finance:'Para Motoru',settings:'Ayarlar'};$('#pageTitle').textContent=titles[view]||'Kontrol Merkezi';$('#contextLabel').textContent=view==='dashboard'?'7 EYLÜL 2026 • BAŞLANGIÇ':longDate(today()).toUpperCase()}
function renderClockContext(){const d=new Date();if(d.getDate()===7&&d.getMonth()===8&&d.getFullYear()===2026)$('#contextLabel').textContent='7 EYLÜL 2026 • BAŞLANGIÇ';}
function assistantInsight(){const d=ensureDay();const mocks=latestMocks('TYT');const todayStudy=studyMinutes(d);const remaining=d.tasks.filter(t=>!t.done);const topWeak=weaknesses()[0];if(todayStudy===0&&remaining.length){return {h:'İlk hamle hazır.',p:`Şu an en yüksek getirili adım: ${remaining[0].title}. 25–50 dakikalık tek odak bloğu başlat.`,a:[['focus','Focus Room’a geç'],['today','Görevleri aç']]}}if(topWeak){return {h:`Radar: ${topWeak.label} geride.`,p:`Son verilere göre ${topWeak.label} alanı risk bölgesinde. Yarınki ilk bloğu buna ayırmak daha mantıklı.`,a:[['roadmap','Konu motoruna git'],['focus','Odak başlat']]}}if(mocks.length<2){return {h:'Ölçüm kuruyoruz.',p:'En geç konu temeli oturmaya başladığında düzenli TYT denemeleri ekle. Deneme olmadan gelişim kördür.',a:[['mock','İlk denemeyi ekle'],['today','Bugünün planı']]}}return {h:'Sistem dengede.',p:`${mocks.at(-1).net.toFixed(2)} netlik son TYT verin var. Bir sonraki amaç, sonucu değil trendi yukarı taşımak.`,a:[['analytics','Trendleri aç'],['discipline','Disiplini kontrol et']]}}
function weaknesses(){const arr=[];const map={'TYT Matematik':'Matematik','TYT Türkçe':'Türkçe','TYT Geometri':'Geometri','TYT Sosyal':'Sosyal','TYT Fen':'Fen','AYT Matematik':'AYT Matematik','AYT Edebiyat':'Edebiyat','AYT Tarih-1':'Tarih-1','AYT Coğrafya-1':'Coğrafya-1'};allSubjects().forEach(([name,topics])=>{const stat=topics.map((_,i)=>stateTopic(name,i));const active=stat.filter(x=>x.status!=='not_started').length;const done=stat.filter(x=>x.status==='done').length;const avg=stat.reduce((a,x)=>a+(x.confidence||0),0)/(stat.length||1);const score=Math.round(done/stat.length*65+active/stat.length*20+avg/5*15);arr.push({label:map[name]||name,score,area:areaOf(name),name,done,active,total:stat.length})});return arr.sort((a,b)=>a.score-b.score)}
function renderDashboard(){const d=ensureDay(),score=systemScore(d),stats=topicStats();$('#scoreBig').textContent=score;$('#scoreBar').style.width=score+'%';$('#studyBig').textContent=studyMinutes(d);$('#studyGoalSmall').textContent=state.settings.studyGoal;$('#streakBig').textContent=streak();$('#countdownBig').textContent='2027';$('#heroDay').textContent=new Intl.DateTimeFormat('tr-TR',{weekday:'short'}).format(new Date()).toUpperCase();$('#heroDate').textContent=pad(new Date().getDate());$('#subjectProgress').style.width=stats.pct+'%';$('#subjectProgressText').textContent=stats.pct+'%';const ai=assistantInsight();$('#assistantHeadline').textContent=ai.h;$('#assistantText').textContent=ai.p;$('#assistantActions').innerHTML=ai.a.map(([v,t])=>`<button data-route="${v}">${t}</button>`).join('');
const rem=d.tasks.filter(t=>!t.done);const top=rem[0];$('#priorityTask').innerHTML=top?`<div class="pri">NEXT BEST ACTION</div><h4>${esc(top.title)}</h4><p>${top.minutes||0} dk • ${esc(top.category)} • Telefonu kapat, tek görev bitir.</p>`:'<div class="pri">SYSTEM COMPLETE</div><h4>Bugünün ana görevleri tamamlandı.</h4><p>Şimdi analiz yap, yarını hazırla.</p>';
$('#remainingTasks').textContent=rem.length;$('#questionProgress').textContent=`${questionCount(d)} / ${state.settings.questionGoal}`;$('#todayCompletion').textContent=taskPct(d)+'%';renderWeeklyChart();renderRecent();renderWeakness();renderDisciplineMini()}
function renderWeeklyChart(){const arr=lastStudyDays(7),max=Math.max(state.settings.studyGoal,...arr.map(x=>x.mins),1),sum=arr.reduce((a,x)=>a+x.mins,0);$('#weeklyStudyLabel').textContent=`${sum} dk`;$('#weeklyChart').innerHTML=arr.map(x=>{const dt=new Date(x.k+'T12:00:00'),name=new Intl.DateTimeFormat('tr-TR',{weekday:'short'}).format(dt).slice(0,3);return `<div class="bar-col"><div class="bar-track"><i style="height:${clamp(Math.round(x.mins/max*100),2,100)}%"></i></div><span>${name}</span><small>${x.mins}</small></div>`}).join('')}
function renderRecent(){const m=state.mocks.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4);$('#recentPerformance').innerHTML=m.length?m.map(x=>`<div class="stack-row"><div><strong>${x.type}</strong><small>${fmtDate(x.date)} • ${x.note?esc(x.note):'analiz notu yok'}</small></div><strong>${x.net.toFixed(2)}</strong></div>`).join(''):'<div class="empty">İlk denemeni kaydettiğinde performans burada görünecek.</div>'}
function renderWeakness(){const w=weaknesses().slice(0,5);$('#weaknessRadar').innerHTML=w.map(x=>`<div class="radar-row"><div class="label">${x.label}</div><div class="radar-bar"><i style="width:${100-x.score}%"></i></div><strong>${100-x.score}</strong></div>`).join('')}
function renderDisciplineMini(){const d=ensureDay(),s=habitScore(d);$('#disciplineMiniScore').textContent=`${s}/5`;$('#disciplineMini').innerHTML=habitDefs.map(([k,n,sub])=>`<div class="discipline-line"><button class="tiny-check ${d.habits[k]?'on':''}" data-habit="${k}">${d.habits[k]?'✓':''}</button><span>${n}<small>${sub}</small></span><small>${d.habits[k]?'Tamam':'Bekliyor'}</small></div>`).join('')}
function renderToday(){const d=ensureDay();$('#taskCountBadge').textContent=`${d.tasks.filter(t=>t.done).length}/${d.tasks.length}`;$('#taskList').innerHTML=d.tasks.map(t=>`<div class="task-item ${t.done?'done':''}"><button class="task-check ${t.done?'on':''}" data-task="${t.id}">${t.done?'✓':''}</button><div><div class="task-title">${esc(t.title)}</div><div class="task-meta">${esc(t.category)} • ${t.kind==='study'?'Akademik':t.kind==='work'?'Para / iş':'Life'} </div></div><div class="task-min">${t.minutes||0} dk</div></div>`).join('');$('#scheduleList').innerHTML=schedule.map(x=>`<div class="schedule-item"><div class="schedule-time">${x[0]}</div><div><strong>${x[2]}</strong><p>${x[3]}</p></div><span>${x[4]}</span></div>`).join('');$('#habitScoreBadge').textContent=`${habitScore(d)}/5`;$('#habitList').innerHTML=habitDefs.map(([k,n,sub])=>`<button class="habit-btn ${d.habits[k]?'on':''}" data-habit="${k}"><span class="hc">${d.habits[k]?'✓':''}</span><strong>${n}</strong><small>${sub}</small></button>`).join('');$('#dayNote').value=d.note||''}
function renderRoadmap(){const area=$('#roadmapArea').value,status=$('#roadmapStatus').value;let total=0,done=0,active=0;$('#roadmapGrid').innerHTML=allSubjects().filter(([name])=>area==='ALL'||areaOf(name)===area).map(([name,topics])=>{const mapped=topics.map((topic,i)=>({topic,i,data:stateTopic(name,i)})).filter(x=>status==='ALL'||x.data.status===status);const localDone=topics.filter((_,i)=>stateTopic(name,i).status==='done').length;const localActive=topics.filter((_,i)=>['learning','practice','review'].includes(stateTopic(name,i).status)).length;total+=topics.length;done+=localDone;active+=localActive;return `<article class="subject-panel"><div class="subject-top"><div><span class="section-kicker">${areaOf(name)}</span><h3>${name}</h3></div><div class="count">${localDone}/${topics.length} tamam</div></div><div class="subject-progress"><i style="width:${Math.round(localDone/topics.length*100)}%"></i></div>${mapped.map(x=>{const c=clamp(Number(x.data.confidence||0),0,5);const s=x.data.status;return `<div class="topic-row"><div><strong>${esc(x.topic)}</strong><small>${topicStatusLabel(s)}${x.data.next?' • tekrar '+fmtDate(x.data.next):''}</small></div><select data-topic="${encodeURIComponent(name)}|${x.i}"><option value="not_started" ${s==='not_started'?'selected':''}>Başlamadı</option><option value="learning" ${s==='learning'?'selected':''}>Çalışılıyor</option><option value="practice" ${s==='practice'?'selected':''}>Soru aşaması</option><option value="review" ${s==='review'?'selected':''}>Tekrar</option><option value="done" ${s==='done'?'selected':''}>Tamamlandı</option></select><div class="confidence" title="Güven ${c}/5">${[1,2,3,4,5].map(i=>`<i class="conf-dot ${i<=c?'on':''}" data-confidence="${encodeURIComponent(name)}|${x.i}|${i}"></i>`).join('')}</div></div>`}).join('')}</article>`}).join('')||'<div class="empty">Filtreye uygun konu bulunamadı.</div>';const p=topicStats();$('#topicTotal').textContent=p.total;$('#topicDone').textContent=p.done;$('#topicActive').textContent=p.active;$('#roadmapProgress').style.width=p.pct+'%';$('#roadmapProgressText').textContent=p.pct+'%'}
const topicStatusLabel=s=>({not_started:'Başlamadı',learning:'Çalışılıyor',practice:'Soru aşaması',review:'Tekrar',done:'Tamamlandı'})[s]||s;
function renderMock(){const m=state.mocks.slice().sort((a,b)=>b.date.localeCompare(a.date));const t=m.filter(x=>x.type==='TYT'),a=m.filter(x=>x.type==='AYT EA');const avg=x=>x.length?(x.reduce((s,y)=>s+y.net,0)/x.length):0;$('#mockKpis').innerHTML=`${[['Toplam',m.length,'deneme'],['TYT ort.',avg(t).toFixed(2),'net'],['AYT EA ort.',avg(a).toFixed(2),'net'],['En iyi TYT',t.length?Math.max(...t.map(x=>x.net)).toFixed(2):'—','net']].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}`;const f=$('#mockFilter').value;const arr=m.filter(x=>f==='ALL'||x.type===f);$('#mockTable').innerHTML=arr.length?`<div class="mock-header"><span>TÜR</span><span>NET</span><span>TARİH</span><span>KIRILIM</span><span></span></div>`+arr.map(x=>`<div class="mock-row"><div><span class="badge ${x.type==='TYT'?'success':'purple'}">${x.type}</span></div><div><strong>${x.net.toFixed(2)}</strong></div><div><span>${fmtDate(x.date)}</span></div><div class="mock-sub"><span>T ${x.breakdown?.turkce??'—'}</span><span>M ${x.breakdown?.math??'—'}</span><span>S ${x.breakdown?.social??'—'}</span><span>F ${x.breakdown?.science??'—'}</span></div><button class="danger-btn" data-delmock="${x.id}">Sil</button></div>`).join(''):'<div class="empty">Deneme yok. İlk kaydınla veri motorunu başlat.</div>'}
function renderAnalytics(){const t=latestMocks('TYT').slice(-10);$('#analyticsKpis').innerHTML=`${[['TYT son',t.length?t.at(-1).net.toFixed(2):'—','net'],['TYT değişim',t.length>1?((t.at(-1).net-t.at(-2).net>=0?'+':'')+(t.at(-1).net-t.at(-2).net).toFixed(2)):'—','son denemeye göre'],['7 gün ders',lastStudyDays(7).reduce((a,x)=>a+x.mins,0),'dk'],['Streak',streak(),'gün']].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}`;$('#netChart').innerHTML=t.length<2?'<div class="empty">Trend için en az 2 TYT denemesi kaydet.</div>':lineSvg(t.map(x=>x.net),t.map(x=>fmtDate(x.date)));const days=lastStudyDays(14),max=Math.max(state.settings.studyGoal,...days.map(x=>x.mins),1);$('#loadChart').innerHTML=days.map(x=>{const dt=new Date(x.k+'T12:00:00'),n=new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'short'}).format(dt);return `<div class="bar-col"><div class="bar-track"><i style="height:${clamp(Math.round(x.mins/max*100),2,100)}%"></i></div><span>${n}</span><small>${x.mins}</small></div>`}).join('');const w=weaknesses()[0];$('#analysisWeak').textContent=w?`${w.label} / ${w.score}/100`: '—';$('#analysisWeakText').textContent=w?`Konu tamamlama + güven verisine göre en kırılgan alan.`:'Konu verisi bekleniyor.';const comp=Math.round(lastStudyDays(7).reduce((a,x)=>a+x.score,0)/7);$('#analysisReliability').textContent=comp+'%';$('#analysisReliabilityText').textContent='Son 7 gün sistem skoru ortalaması.';const active=lastStudyDays(30).filter(x=>x.d&&systemScore(x.d)>=40).length;$('#analysisConsistency').textContent=active+'/30';$('#analysisConsistencyText').textContent='Son 30 günde ≥40 skor alınan gün.'}
function lineSvg(vals,labels){const w=700,h=270,p=35,min=Math.min(...vals),max=Math.max(...vals),range=Math.max(max-min,1);const pts=vals.map((v,i)=>{const x=p+i*(w-2*p)/Math.max(1,vals.length-1),y=h-p-(v-min)/range*(h-2*p);return [x,y]});const d=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+','+p[1].toFixed(1)).join(' ');return `<svg viewBox="0 0 ${w} ${h}" role="img"><path d="M${p} ${h-p} H${w-p}" stroke="#252e3e"/><path d="${d}" fill="none" stroke="url(#g)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#b7ff5a"/><stop offset="1" stop-color="#63e6be"/></linearGradient></defs>${pts.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="5" fill="#0e151d" stroke="#b7ff5a" stroke-width="3"><title>${labels[i]} • ${vals[i]}</title></circle>`).join('')}</svg>`}
function renderDiscipline(){const days=lastStudyDays(30);$('#disciplineHeatmap').innerHTML=days.map(x=>`<div class="heat-cell ${heatClass(x.score)}" title="${fmtDate(x.k)} • ${x.score}"></div>`).join('');$('#disciplineCards').innerHTML=`<article class="card"><span class="section-kicker">CURRENT</span><h3>${systemScore(ensureDay())}/100</h3><p class="muted">Bugünün sistem skoru.</p></article><article class="card"><span class="section-kicker">7 DAY AVG</span><h3>${Math.round(days.slice(-7).reduce((a,x)=>a+x.score,0)/7)}%</h3><p class="muted">Son 7 gün ortalaması.</p></article><article class="card"><span class="section-kicker">STREAK</span><h3>${streak()} gün</h3><p class="muted">70+ skorla kırılmadan devam.</p></article>`}
function heatClass(s){return s>=85?'h4':s>=70?'h3':s>=40?'h2':s>0?'h1':''}
function monthMoney(){const ym=today().slice(0,7);const inc=state.money.filter(x=>x.date.startsWith(ym)&&x.type==='income').reduce((s,x)=>s+x.amount,0);const exp=state.money.filter(x=>x.date.startsWith(ym)&&x.type==='expense').reduce((s,x)=>s+x.amount,0);return {inc,exp,net:BASE_SALARY+inc-exp}}
function renderFinance(){const m=monthMoney();$('#financeKpis').innerHTML=`${[['Sabit gelir','₺'+BASE_SALARY.toLocaleString('tr-TR'),'Spor salonu'],['Ek gelir','₺'+m.inc.toLocaleString('tr-TR'),'Bu ay'],['Gider','₺'+m.exp.toLocaleString('tr-TR'),'Bu ay'],['Net nakit','₺'+m.net.toLocaleString('tr-TR'),'Takip edilen']].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}`;const rows=[['Maaş',BASE_SALARY],['Ek gelir',m.inc],['Gider',-m.exp]];const max=Math.max(BASE_SALARY,m.inc,m.exp,1);$('#cashflowBars').innerHTML=`<div class="finance-stack">${rows.map(r=>`<div class="cash-line"><span>${r[0]}</span><div class="cash-track"><i style="width:${Math.max(3,Math.round(Math.abs(r[1])/max*100))}%"></i></div><strong>${r[1]<0?'-':''}₺${Math.abs(r[1]).toLocaleString('tr-TR')}</strong></div>`).join('')}</div>`;$('#moneyList').innerHTML=state.money.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,20).map(x=>`<div class="money-item"><div><strong>${esc(x.desc)}</strong><small>${fmtDate(x.date)} • ${x.type==='income'?'Gelir':'Gider'}</small></div><strong class="${x.type==='income'?'income':'expense'}">${x.type==='income'?'+':'-'}₺${x.amount.toLocaleString('tr-TR')}</strong></div>`).join('')||'<div class="empty">Henüz para hareketi yok.</div>'}
function renderSettings(){$('#setStudy').value=state.settings.studyGoal;$('#setQuestions').value=state.settings.questionGoal;$('#setParagraph').value=state.settings.paragraphGoal;$('#setProblem').value=state.settings.problemGoal}
function renderAll(){applyTheme();ensureDay();renderDashboard();renderToday();renderRoadmap();renderMock();renderAnalytics();renderDiscipline();renderFinance();renderSettings();renderClockContext()}
function addTask(){const d=ensureDay();const title=$('#taskTitle').value.trim();if(!title)return;const cat=$('#taskCategory').value;d.tasks.push({id:uid('task'),title,category:cat,minutes:Number($('#taskMinutes').value)||0,kind:['TYT','AYT','Tekrar'].includes(cat)?'study':cat==='EB Digital'?'work':'life',done:false});save();$('#taskDialog').close();$('#taskForm').reset();renderAll();toast('Görev eklendi.')}
function addMock(){const type=$('#mockType').value,net=Number($('#mockNet').value);if(!net)return;state.mocks.push({id:uid('mock'),type,net,date:$('#mockDate').value||today(),note:$('#mockNote').value.trim(),duration:Number($('#mockDuration').value)||0,breakdown:{turkce:valOrNull($('#mockTurkce').value),math:valOrNull($('#mockMath').value),social:valOrNull($('#mockSocial').value),science:valOrNull($('#mockScience').value)}});save();$('#mockDialog').close();$('#mockForm').reset();$('#mockDate').value=today();renderAll();toast('Deneme performansa işlendi.')}
function valOrNull(v){return v===''?null:Number(v)}
function addMoney(typeOverride){$('#moneyType').value=typeOverride||'income';$('#moneyDialog').showModal()}
function saveMoney(){const desc=$('#moneyDesc').value.trim(),amt=Number($('#moneyAmount').value),type=$('#moneyType').value;if(!desc||!amt)return;state.money.push({id:uid('money'),type,desc,amount:amt,date:today()});save();$('#moneyDialog').close();$('#moneyForm').reset();renderAll();toast(type==='income'?'Gelir kaydedildi.':'Gider kaydedildi.')}
function saveNote(){const d=ensureDay();d.note=$('#dayNote').value.trim();save();toast('Günün notu kaydedildi.')}
function finishDay(){const d=ensureDay();const next=d.tasks.find(t=>!t.done);if(next){toast('Günü kapatmak için açık görevler var.')}else{d.habits.study=true;save();renderAll();toast('Gün kapatıldı. Güzel iş.')}}
function optimizePlan(){const d=ensureDay();const weak=weaknesses()[0];const open=d.tasks.filter(t=>!t.done);if(weak&&weak.area==='AYT'){d.tasks=d.tasks.map(t=>t.title.startsWith('AYT Edebiyat')?{...t,title:'AYT Odak • '+weak.label+' • 60 dk'}:t)}else if(open.length){open[0].minutes=Math.max(open[0].minutes||30,45)}save();renderAll();toast('Plan veri durumuna göre optimize edildi.')}
function setTopic(name,i,status){state.subjects[name]??={};const prev=stateTopic(name,i);state.subjects[name][i]={...prev,status,last:today(),next:status==='done'?addDays(today(),7):status==='review'?addDays(today(),14):prev.next||''};save()}
function setConfidence(name,i,c){state.subjects[name]??={};const prev=stateTopic(name,i);state.subjects[name][i]={...prev,confidence:c,last:today()};save()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`hukuk-50k-os-${today()}.json`;a.click();URL.revokeObjectURL(url);toast('Yedek indiriliyor.')}
function importData(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x||!x.version)throw Error();state=normalize(x);save();renderAll();toast('Yedek başarıyla yüklendi.')}catch{toast('Geçersiz yedek.')}};r.readAsText(file)}
function setFocusTimer(mins=25){focus.total=mins*60;focus.left=focus.total;focus.running=false;renderTimer()}
const focus={total:1500,left:1500,running:false,handle:null,taskId:null};
function renderTimer(){const m=Math.floor(focus.left/60),s=focus.left%60;$('#timerDisplay').textContent=`${pad(m)}:${pad(s)}`;const pct=focus.total?((focus.total-focus.left)/focus.total)*360:0;$('#focus .focus-ring').style.background=`conic-gradient(var(--accent) ${pct}deg,#1a2230 ${pct}deg)`}
function startTimer(){if(focus.running)return;focus.running=true;focus.handle=setInterval(()=>{if(focus.left<=0){stopTimer();state.focusSessions++;save();toast('Focus bloğu tamamlandı. Kayda geçti.');return}focus.left--;renderTimer()},1000)}
function stopTimer(){focus.running=false;clearInterval(focus.handle);focus.handle=null;renderTimer()}
function resetTimer(){stopTimer();setFocusTimer(25)}
function commandResults(q){const commands=[['Bugünün sistemini aç','today'],['Focus Room','focus'],['Konu motoru','roadmap'],['Deneme merkezi','mock'],['Performans','analytics'],['Disiplin','discipline'],['Para motoru','finance'],['Ayarlar','settings']];const f=commands.filter(x=>x[0].toLowerCase().includes(q.toLowerCase()));$('#commandResults').innerHTML=f.map(x=>`<button class="command-item" data-route="${x[1]}"><strong>${x[0]}</strong><span>↵ aç</span></button>`).join('')||'<div class="empty">Komut bulunamadı.</div>'}
// Events
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
document.addEventListener('click',e=>{const route=e.target.closest('[data-route]');if(route){navigate(route.dataset.route);const dlg=$('#commandDialog');if(dlg.open)dlg.close();return}const task=e.target.closest('[data-task]');if(task){const d=ensureDay();const t=d.tasks.find(x=>x.id===task.dataset.task);if(t){t.done=!t.done;save();renderAll();toast(t.done?'Görev tamamlandı.':'Görev geri açıldı.');}}const hb=e.target.closest('[data-habit]');if(hb){const d=ensureDay();d.habits[hb.dataset.habit]=!d.habits[hb.dataset.habit];save();renderAll()}const del=e.target.closest('[data-delmock]');if(del){state.mocks=state.mocks.filter(m=>m.id!==del.dataset.delmock);save();renderAll();toast('Deneme silindi.')}const conf=e.target.closest('[data-confidence]');if(conf){const [name,i,c]=decodeURIComponent(conf.dataset.confidence).split('|');setConfidence(name,Number(i),Number(c));renderRoadmap();toast(`Güven seviyesi ${c}/5.`)}});
$('#addTask').onclick=()=>$('#taskDialog').showModal();$('#taskForm').onsubmit=e=>{e.preventDefault();addTask()};$('#addMock').onclick=()=>{$('#mockDate').value=today();$('#mockDialog').showModal()};$('#mockForm').onsubmit=e=>{e.preventDefault();addMock()};$('#addIncomeQuick').onclick=()=>addMoney('income');$('#addExpenseQuick').onclick=()=>addMoney('expense');$('#moneyForm').onsubmit=e=>{e.preventDefault();saveMoney()};$('#finishDay').onclick=finishDay;$('#regeneratePlan').onclick=optimizePlan;$('#saveDayNote').onclick=saveNote;
$('#roadmapArea').onchange=renderRoadmap;$('#roadmapStatus').onchange=renderRoadmap;$('#mockFilter').onchange=renderMock;
document.addEventListener('change',e=>{const s=e.target.closest('[data-topic]');if(s){const [name,i]=decodeURIComponent(s.dataset.topic).split('|');setTopic(name,Number(i),s.value);renderRoadmap();renderDashboard()}});
$('#saveSettings').onclick=()=>{state.settings.studyGoal=clamp(Number($('#setStudy').value)||270,120,720);state.settings.questionGoal=clamp(Number($('#setQuestions').value)||350,50,1000);state.settings.paragraphGoal=clamp(Number($('#setParagraph').value)||20,0,100);state.settings.problemGoal=clamp(Number($('#setProblem').value)||15,0,100);save();renderAll();toast('Hedefler güncellendi.')};$('#exportTop').onclick=exportData;$('#exportSettings').onclick=exportData;$('#importSettings').onchange=e=>{const f=e.target.files?.[0];if(f)importData(f)};$('#resetSettings').onclick=()=>{if(confirm('Tüm takip verileri silinecek. Emin misin?')){state=clone(defaultState);save();renderAll();toast('Veriler sıfırlandı.')}};
$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();applyTheme()};$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');
$('#focusTaskSelect').onclick=()=>{const d=ensureDay(),open=d.tasks.filter(t=>!t.done);if(!open.length){toast('Açık görev kalmadı.');return}focus.taskId=open[0].id;$('#focusTargetLabel').textContent=open[0].title;$('#focusSelected').textContent=`Seçildi • ${open[0].minutes||25} dk • ${open[0].category}`;setFocusTimer(Math.min(50,Math.max(25,Math.round((open[0].minutes||25)/5)*5)))};
$('#timerStart').onclick=startTimer;$('#timerPause').onclick=stopTimer;$('#timerReset').onclick=resetTimer;
$('#globalSearch').onfocus=()=>{$('#commandDialog').showModal();$('#commandInput').focus()};$('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('#commandDialog').showModal();$('#commandInput').focus()}};$('#commandInput').oninput=e=>commandResults(e.target.value);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#commandDialog').showModal();$('#commandInput').focus();commandResults('')}});
$('#commandDialog').addEventListener('close',()=>{$('#globalSearch').value=''});
setFocusTimer(25);ensureDay();renderAll();
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}
