const KEY='hukuk50k-os-v2';
const START='2026-09-07';
const $=(s)=>document.querySelector(s);
const $$=(s)=>[...document.querySelectorAll(s)];
const iso=(d)=>{const x=new Date(d);return new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const todayKey=()=>iso(new Date());
const addDays=(key,n)=>{const d=new Date(key+'T12:00:00');d.setDate(d.getDate()+n);return iso(d)};
const fmtDate=(k)=>new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'short',weekday:'short'}).format(new Date(k+'T12:00:00'));
const esc=(s)=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=(p='id')=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const curriculum={
 'TYT Matematik':['Temel Kavramlar','Sayı Basamakları','Bölme-Bölünebilme','EBOB-EKOK','Rasyonel Sayılar','Üslü Sayılar','Köklü Sayılar','Mutlak Değer','Basit Eşitsizlikler','Oran-Orantı','Denklem Çözme','Problemler','Kümeler','Fonksiyonlar','Permütasyon-Kombinasyon','Olasılık','Veri-İstatistik'],
 'TYT Türkçe':['Sözcükte Anlam','Cümlede Anlam','Paragraf','Ses Bilgisi','Yazım Kuralları','Noktalama','Sözcük Türleri','Fiil-Ekler','Cümlenin Ögeleri','Cümle Türleri','Anlatım Bozukluğu'],
 'TYT Geometri':['Doğruda Açılar','Üçgende Açılar','Üçgende Uzunluk','Üçgenlerde Alan','Benzerlik','Çokgenler','Dörtgenler','Çember-Daire','Katı Cisimler','Analitik Geometri'],
 'TYT Fen':['Fizik Temelleri','Hareket-Kuvvet','İş-Güç-Enerji','Elektrik','Kimyanın Temelleri','Atom ve Periyodik Sistem','Kimyasal Türler','Maddenin Halleri','Biyoloji Bilimine Giriş','Hücre','Canlıların Sınıflandırılması','Kalıtım'],
 'TYT Sosyal':['Tarih Bilimine Giriş','İlk Türk Devletleri','İslam Tarihi','Osmanlı Siyasi Tarihi','Milli Mücadele','Atatürk İlkeleri','Coğrafyanın Temelleri','Türkiye Coğrafyası','Felsefeye Giriş','Din Kültürü Temelleri'],
 'AYT Matematik':['Fonksiyonlar','Polinomlar','İkinci Dereceden Denklemler','Parabol','Eşitsizlikler','Trigonometri','Üstel ve Logaritmik Fonksiyonlar','Diziler','Permütasyon-Kombinasyon','Olasılık','Limit ve Süreklilik','Türev','İntegral','Analitik Geometri'],
 'AYT Edebiyat':['Edebiyat Bilgisi','Şiir Bilgisi','İslamiyet Öncesi Türk Edebiyatı','Geçiş Dönemi','Halk Edebiyatı','Divan Edebiyatı','Tanzimat','Servetifünun','Fecriati','Milli Edebiyat','Cumhuriyet Dönemi','Şiir Akımları','Roman-Hikâye','Tiyatro','Edebi Sanatlar'],
 'AYT Tarih-1':['Tarih ve Zaman','İlk ve Orta Çağlarda Türk Dünyası','Osmanlı Siyasi Tarihi','Osmanlı Kültür ve Medeniyeti','18-19. Yüzyıl Osmanlı','Milli Mücadele','Atatürk Dönemi İç ve Dış Politika'],
 'AYT Coğrafya-1':['Doğal Sistemler','Beşeri Sistemler','Ekonomik Faaliyetler','Türkiye Coğrafyası','Küresel Ortam','Çevre ve Toplum']
};
const area=(name)=>name.startsWith('TYT')?'TYT':'AYT';
const starterTasks=[
 {title:'TYT Matematik • 120 dk',category:'TYT',minutes:120},
 {title:'Türkçe • 20 paragraf + yanlış analizi',category:'TYT',minutes:45},
 {title:'AYT Edebiyat • 60 dk',category:'AYT',minutes:60},
 {title:'Problem • 15 soru',category:'Tekrar',minutes:30},
 {title:'EB Digital Studio • müşteri/portföy',category:'EB Digital',minutes:60},
 {title:'Antrenman',category:'Spor',minutes:60}
];
const blocks=[['08:30','10:30','TYT Matematik','120 dk • konu + soru'],['10:45','12:15','Türkçe / AYT Edebiyat','90 dk • aktif çalışma'],['12:15','12:45','Paragraf + Problem','30 dk • günlük taban'],['13:30','14:30','EB Digital Studio','60 dk • para motoru'],['15:00','15:30','Mini tekrar','30 dk • yanlışlar / kartlar']];
const habitDefs=[['sleep','7+ saat uyku'],['study','Günlük ders hedefi'],['phone','Sosyal medya ≤45 dk'],['exercise','Antrenman / yürüyüş'],['eb','EB Digital 60 dk']];
const defaultState={version:2,days:{},subjects:{},mocks:[],money:[],settings:{studyGoal:270,paragraphGoal:20,problemGoal:15},theme:'dark'};
let state=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&x.version===2?x:structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function ensureDay(k=todayKey()){if(!state.days[k])state.days[k]={tasks:starterTasks.map(x=>({...x,id:uid('t'),done:false})),habits:{sleep:false,study:false,phone:false,exercise:false,eb:false},studyMinutes:0};return state.days[k]}
function studyFromTasks(d){return d.tasks.filter(x=>x.done&&['TYT','AYT','Tekrar'].includes(x.category)).reduce((s,x)=>s+(Number(x.minutes)||0),0)}
function taskPct(d){return d.tasks.length?Math.round(d.tasks.filter(x=>x.done).length/d.tasks.length*100):0}
function streak(){let n=0,k=todayKey();while(state.days[k]){const d=state.days[k],p=taskPct(d);if(p<70)break;n++;k=addDays(k,-1)}return n}
function renderClock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}
function setSection(section){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===section));$$('.section').forEach(s=>s.classList.toggle('active',s.id===section));const titles={dashboard:'Kontrol Merkezi',today:'Bugünkü Plan',subjects:'Konu Yol Haritası',mock:'Deneme Merkezi',analytics:'Performans Analizi',habits:'Disiplin Merkezi',money:'Para Merkezi',settings:'Sistem Ayarları'};$('#pageTitle').textContent=titles[section]||'Kontrol Merkezi'}
function renderDashboard(){const d=ensureDay(),p=taskPct(d),study=studyFromTasks(d);$('#dailyPercent').textContent=p;$('#ringValue').textContent=p+'%';$('#dailyLine').style.width=p+'%';$('#progressRing').style.setProperty('--deg',`${p*3.6}deg`);$('#dailySummary').textContent=p===100?'Bugünün sistemi tamamlandı.':`${d.tasks.filter(x=>!x.done).length} görev kaldı.`;$('#studyMetric').textContent=study;$('#studyGoal').textContent=state.settings.studyGoal;$('#streakMetric').textContent=streak();const tyts=state.mocks.filter(x=>x.type==='TYT').sort((a,b)=>a.date.localeCompare(b.date));if(tyts.length){const last=tyts.at(-1),prev=tyts.at(-2);$('#lastTyt').textContent=last.net.toFixed(2);$('#tytDelta').textContent=prev?`${(last.net-prev.net>=0?'+':'')+(last.net-prev.net).toFixed(2)} son denemeye göre`:`${fmtDate(last.date)}`}else{$('#lastTyt').textContent='—';$('#tytDelta').textContent='Henüz deneme yok'}$('#dashTasks').innerHTML=d.tasks.slice(0,6).map(taskHtml).join('');$('#weeklyBars').innerHTML=weekBars();$('#goalCard').innerHTML=`<div class="goal-big"><strong>İLK 50K</strong><span>Hukuk</span></div><div class="goal-row"><span>Başlangıç</span><strong>07.09.2026</strong></div><div class="goal-row"><span>Günlük ders</span><strong>${state.settings.studyGoal} dk</strong></div><div class="goal-row"><span>EA ana odak</span><strong>AYT Mat + Edebiyat</strong></div>`;$('#recentMocks').innerHTML=state.mocks.length?state.mocks.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4).map(mockMini).join(''):'<p class="muted">İlk denemeni kaydettiğinde burada görünecek.</p>';renderDashHabits()}
function taskHtml(t){return `<div class="task ${t.done?'done':''}"><button class="check ${t.done?'checked':''}" data-task="${t.id}">${t.done?'✓':''}</button><div><div class="title">${esc(t.title)}</div><div class="task-meta">${esc(t.category)}${t.minutes?' • '+t.minutes+' dk':''}</div></div><span class="tag">${t.done?'Tamam':'Açık'}</span></div>`}
function renderToday(){const d=ensureDay();$('#todayDateText').textContent=new Intl.DateTimeFormat('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());$('#taskCount').textContent=`${d.tasks.filter(x=>x.done).length}/${d.tasks.length}`;$('#taskList').innerHTML=d.tasks.map(taskHtml).join('');$('#todayBlocks').innerHTML=blocks.map(b=>`<div class="time-block"><time>${b[0]}</time><div><strong>${b[2]}</strong><p>${b[3]}</p></div><span>${b[1]}</span></div>`).join('');const scored=habitDefs.filter(([k])=>d.habits[k]).length;$('#habitScore').textContent=`${scored}/${habitDefs.length}`;$('#habitChecklist').innerHTML=habitDefs.map(([k,n])=>`<button class="habit-line ${d.habits[k]?'done':''}" data-habit="${k}"><span class="check mini">${d.habits[k]?'✓':''}</span><strong>${n}</strong><span>${d.habits[k]?'Tamam':'İşaretle'}</span></button>`).join('')}
function renderSubjects(){const sf=$('#subjectFilter').value,st=$('#statusFilter').value;let done=0,total=0;$('#subjectGrid').innerHTML=Object.entries(curriculum).filter(([name])=>sf==='all'||area(name)===sf).map(([name,topics])=>{const vals=state.subjects[name]||{};const filtered=topics.map((tp,i)=>({tp,i,status:vals[i]||'not_started'})).filter(x=>st==='all'||x.status===st);total+=topics.length;done+=topics.filter((_,i)=>vals[i]==='done').length;return `<article class="subject-card"><div class="subject-head"><div><span class="tag">${area(name)}</span><h3>${name}</h3></div><strong>${topics.filter((_,i)=>vals[i]==='done').length}/${topics.length}</strong></div><div class="subject-mini-bar"><i style="width:${Math.round(topics.filter((_,i)=>vals[i]==='done').length/topics.length*100)}%"></i></div>${filtered.map(x=>`<div class="topic ${x.status}"><div><strong>${x.tp}</strong><small>${statusLabel(x.status)}</small></div><select data-topic="${encodeURIComponent(name)}|${x.i}"><option value="not_started" ${x.status==='not_started'?'selected':''}>Başlamadı</option><option value="learning" ${x.status==='learning'?'selected':''}>Çalışılıyor</option><option value="done" ${x.status==='done'?'selected':''}>Bitti</option></select></div>`).join('')}</article>`}).join('');const pct=total?Math.round(done/total*100):0;$('#subjectPct').textContent=pct+'%';$('#subjectBar').style.width=pct+'%'}
const statusLabel=(s)=>s==='done'?'Bitti':s==='learning'?'Çalışılıyor':'Başlamadı';
function renderMocks(){const arr=state.mocks.slice().sort((a,b)=>b.date.localeCompare(a.date));const t=arr.filter(x=>x.type==='TYT'),a=arr.filter(x=>x.type==='AYT EA');$('#mockSummary').innerHTML=`<div class="summary-chip"><span>TYT deneme</span><strong>${t.length}</strong></div><div class="summary-chip"><span>AYT deneme</span><strong>${a.length}</strong></div><div class="summary-chip"><span>En yüksek TYT</span><strong>${t.length?Math.max(...t.map(x=>x.net)).toFixed(2):'—'}</strong></div>`;$('#mockList').innerHTML=arr.length?arr.map((m,i)=>`<div class="mock-row"><div><span class="tag">${m.type}</span><strong>${m.net.toFixed(2)} net</strong><small>${fmtDate(m.date)}${m.note?' • '+esc(m.note):''}</small></div><div class="mock-breakdown"><span>T ${m.breakdown?.turkce??'—'}</span><span>M ${m.breakdown?.math??'—'}</span><span>S ${m.breakdown?.social??'—'}</span><span>F ${m.breakdown?.science??'—'}</span></div><button class="delete-btn" data-delmock="${m.id}">Sil</button></div>`).join(''):'<div class="empty">Henüz deneme yok. İlk denemeyi gir.</div>'}
function mockMini(m){return `<div class="mini-row"><div><span>${m.type}</span><small>${fmtDate(m.date)}</small></div><strong>${m.net.toFixed(2)}</strong></div>`}
function weekBars(){const names=['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'];let out='';const mon=new Date();const day=(mon.getDay()+6)%7;mon.setDate(mon.getDate()-day);for(let i=0;i<7;i++){const k=iso(mon);const d=state.days[k];const mins=d?studyFromTasks(d):0;const pct=Math.min(100,Math.round(mins/state.settings.studyGoal*100));out+=`<div class="week-col"><div class="bar-wrap"><i class="study" style="height:${Math.max(5,pct)}%"></i></div><span>${names[i]}</span><small>${mins}dk</small></div>`;mon.setDate(mon.getDate()+1)}return out}
function renderDashHabits(){const d=ensureDay();$('#dashHabits').innerHTML=habitDefs.map(([k,n])=>`<div class="dash-habit"><span class="dot ${d.habits[k]?'on':''}"></span>${n}<strong>${d.habits[k]?'✓':'—'}</strong></div>`).join('')}
function renderAnalytics(){const t=state.mocks.filter(x=>x.type==='TYT').slice().sort((a,b)=>a.date.localeCompare(b.date)).slice(-10);$('#tytChart').innerHTML=t.length?svgLine(t.map(x=>x.net),t.map(x=>fmtDate(x.date))):'<div class="empty">En az 2 TYT denemesiyle trend belirginleşir.</div>';const days=[];for(let i=6;i>=0;i--){const k=addDays(todayKey(),-i),d=state.days[k];days.push({k,mins:d?studyFromTasks(d):0})}const max=Math.max(state.settings.studyGoal,...days.map(x=>x.mins),1);$('#studyChart').innerHTML=days.map(x=>`<div class="study-bar"><span>${fmtDate(x.k)}</span><div><i style="width:${Math.round(x.mins/max*100)}%"></i></div><strong>${x.mins}dk</strong></div>`).join('');const entries=[];Object.entries(curriculum).forEach(([name,topics])=>topics.forEach((t,i)=>{const s=state.subjects[name]?.[i];if(s==='learning')entries.push(`${name} • ${t}`)}));$('#weakTopic').textContent=entries[0]||'Henüz veri yok';$('#strongSubject').textContent=studyFromTasks(ensureDay())>0?'TYT/AYT planlı çalışma':'Henüz veri yok';const compliance=lastNDays(7).reduce((a,k)=>a+taskPct(state.days[k]||{tasks:[]}),0)/7;$('#weeklyCompliance').textContent=Math.round(compliance)+'%';$('#weeklyComplianceHint').textContent='Son 7 gün ortalama görev uyumu.'}
function svgLine(vals,labels){const w=640,h=230,p=28,max=Math.max(...vals,1),min=Math.min(...vals,0),range=Math.max(1,max-min),pts=vals.map((v,i)=>`${p+i*((w-p*2)/Math.max(1,vals.length-1))},${h-p-((v-min)/range)*(h-p*2)}`).join(' ');return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="TYT net trendi"><polyline class="chart-grid" points="${p},${h-p} ${w-p},${h-p}"/><polyline class="chart-line" points="${pts}"/>${vals.map((v,i)=>{const [x,y]=pts.split(' ')[i].split(',');return `<circle class="chart-point" cx="${x}" cy="${y}" r="5"><title>${labels[i]} • ${v}</title></circle>`}).join('')}</svg>`}
function renderHabits(){const days=lastNDays(14).map(k=>({k,d:state.days[k]}));$('#habitCalendar').innerHTML=days.map(x=>{const p=x.d?taskPct(x.d):0;const cls=p>=85?'great':p>=70?'good':p>=40?'mid':'low';return `<div class="day-box ${cls}" title="${fmtDate(x.k)} • ${p}%"><span>${new Date(x.k+'T12:00').getDate()}</span><small>${p}%</small></div>`}).join('');const completed=days.reduce((s,x)=>s+(x.d?x.d.tasks.filter(t=>t.done).length:0),0);const total=days.reduce((s,x)=>s+(x.d?x.d.tasks.length:0),0);$('#habitStats').innerHTML=`<article class="panel"><span class="muted">14 günlük görev</span><h3>${total?Math.round(completed/total*100):0}% uyum</h3></article><article class="panel"><span class="muted">En uzun streak</span><h3>${streak()} gün</h3></article><article class="panel"><span class="muted">Bugün</span><h3>${taskPct(ensureDay())}% tamam</h3></article>`}
function renderMoney(){const m=todayKey().slice(0,7),inc=state.money.filter(x=>x.date.startsWith(m)&&x.type==='income').reduce((s,x)=>s+x.amount,0),exp=state.money.filter(x=>x.date.startsWith(m)&&x.type==='expense').reduce((s,x)=>s+x.amount,0);$('#extraIncome').textContent='₺'+inc.toLocaleString('tr-TR');$('#expenseTotal').textContent='₺'+exp.toLocaleString('tr-TR');$('#netMoney').textContent='₺'+(15000+inc-exp).toLocaleString('tr-TR');$('#moneyList').innerHTML=state.money.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,12).map(x=>`<div class="money-item"><div><strong>${esc(x.desc)}</strong><small>${fmtDate(x.date)} • ${x.type==='income'?'Gelir':'Gider'}</small></div><strong class="${x.type==='income'?'income':'expense'}">${x.type==='income'?'+':'-'}₺${x.amount.toLocaleString('tr-TR')}</strong></div>`).join('')||'<div class="empty">Henüz para hareketi yok.</div>'}
function renderSettings(){$('#studyGoalInput').value=state.settings.studyGoal;$('#paragraphGoalInput').value=state.settings.paragraphGoal;$('#problemGoalInput').value=state.settings.problemGoal}
function renderAll(){renderDashboard();renderToday();renderSubjects();renderMocks();renderAnalytics();renderHabits();renderMoney();renderSettings();applyTheme();renderClock()}
function lastNDays(n){const out=[];for(let i=n-1;i>=0;i--)out.push(addDays(todayKey(),-i));return out}
function addTask(){const d=ensureDay();d.tasks.push({id:uid('t'),title:$('#taskTitle').value.trim(),category:$('#taskCategory').value,minutes:Number($('#taskMinutes').value)||0,done:false});save();$('#taskDialog').close();$('#taskForm').reset();renderAll()}
function addMock(){state.mocks.push({id:uid('m'),type:$('#mockType').value,net:Number($('#mockNet').value),date:todayKey(),note:$('#mockNote').value.trim(),breakdown:{turkce:Number($('#mockTurkce').value)||null,math:Number($('#mockMath').value)||null,social:Number($('#mockSocial').value)||null,science:Number($('#mockScience').value)||null}});save();$('#mockDialog').close();$('#mockForm').reset();renderAll()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`hukuk-50k-yks-${todayKey()}.json`;a.click();URL.revokeObjectURL(url)}
function applyTheme(){document.documentElement.dataset.theme=state.theme||'dark';$('#themeBtn').textContent=state.theme==='dark'?'☼':'☾'}

document.addEventListener('click',e=>{const nav=e.target.closest('.nav-item');if(nav)setSection(nav.dataset.section);const tb=e.target.closest('[data-task]');if(tb){const d=ensureDay();const t=d.tasks.find(x=>x.id===tb.dataset.task);if(t){t.done=!t.done;save();renderAll()}}const hb=e.target.closest('[data-habit]');if(hb){const d=ensureDay();d.habits[hb.dataset.habit]=!d.habits[hb.dataset.habit];save();renderAll()}const dm=e.target.closest('[data-delmock]');if(dm){state.mocks=state.mocks.filter(m=>m.id!==dm.dataset.delmock);save();renderAll()}});
$('#goToday').onclick=()=>setSection('today');$('#addTaskBtn').onclick=()=>$('#taskDialog').showModal();$('#taskForm').onsubmit=e=>{e.preventDefault();addTask()};$('#addMockBtn').onclick=()=>$('#mockDialog').showModal();$('#mockForm').onsubmit=e=>{e.preventDefault();addMock()};$('#completeAllBtn').onclick=()=>{const d=ensureDay();d.tasks.forEach(t=>t.done=true);d.habits.study=true;save();renderAll()};$('#exportBtn').onclick=exportData;$('#exportBtn2').onclick=exportData;
$('#addMoneyBtnTop').onclick=()=>$('#moneyDesc').focus();$('#addMoneyBtn').onclick=()=>{const desc=$('#moneyDesc').value.trim(),amt=Number($('#moneyAmount').value);if(!desc||!amt)return;state.money.push({id:uid('cash'),desc,amount:amt,type:$('#moneyType').value,date:todayKey()});save();$('#moneyDesc').value='';$('#moneyAmount').value='';renderAll()};
$('#subjectFilter').onchange=renderSubjects;$('#statusFilter').onchange=renderSubjects;document.addEventListener('change',e=>{const s=e.target.closest('[data-topic]');if(s){const [name,i]=decodeURIComponent(s.dataset.topic).split('|');state.subjects[name]??={};state.subjects[name][i]=s.value;save();renderAll()}});
$('#saveSettingsBtn').onclick=()=>{state.settings.studyGoal=Math.max(60,Number($('#studyGoalInput').value)||270);state.settings.paragraphGoal=Math.max(0,Number($('#paragraphGoalInput').value)||20);state.settings.problemGoal=Math.max(0,Number($('#problemGoalInput').value)||15);save();renderAll()};$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();applyTheme()};$('#resetBtn').onclick=()=>{if(confirm('Tüm YKS takip verileri silinecek. Emin misin?')){state=structuredClone(defaultState);save();renderAll()}};$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x||!x.version)throw 0;state=x;save();renderAll();alert('Yedek başarıyla yüklendi.')}catch{alert('Geçersiz yedek dosyası.')}};r.readAsText(f)};
setInterval(renderClock,1000);renderAll();
